- op: add
  path: /webhooks/0/namespaceSelector
  value:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          [
            "kube-system",
            "cert-manager",
            "dragonfly-system",
            "dragonfly-injector-system", # TODO: this namespace is webhook self
          ]
