- op: add
  path: /webhooks/0/namespaceSelector
  value:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          [
            "kube-system",
            "kube-public",
            "cert-manager",
            "dragonfly-system",
            "dragonfly-p2p-webhook-system",
          ]
