name: Tests

on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run Tests
        run: |
          go mod tidy
          make test
